security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users: "%users%"

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous:                ~
            form_login:
                check_path:           kimai_auth_security_check
                login_path:           kimai_auth_security_login
                default_target_path:  kimai_core_default_index
                provider:             in_memory
            logout:
                path:                 kimai_auth_security_logout
                target:               kimai_core_default_index
            remember_me:
                key:                  "%secret%"
            pattern:                  ^/

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
